services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.4
    container_name: elasticsearch_test
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false

  eslasticsearch-init:
    build: ./elasticsearch-init
    depends_on:
      - elasticsearch
    environment:
      - FORCE_REINDEX=false
    volumes:
      - ./elasticsearch-init/data/dataset.jsonl:/opt/app/data/dataset.jsonl
      - ../embeddings:/opt/app/embeddings
    working_dir: /opt/app
    command: [ "python", "/opt/app/elasticsearch_init.py" ]

